# Generated by Django 2.2.9 on 2020-01-09 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200109_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='akcja',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.SlAkcja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='nieruchomosc',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.SlNieruchomosci'),
            preserve_default=False,
        ),
    ]
