# Generated by Django 2.2.9 on 2020-01-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200109_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='slakcja',
            name='nazwa',
            field=models.CharField(max_length=120, verbose_name='Sposób nabycia/wykorzystania'),
        ),
        migrations.AlterField(
            model_name='slnieruchomosci',
            name='nazwa',
            field=models.CharField(max_length=120, verbose_name='Typ nieruchomości'),
        ),
    ]
