# Generated by Django 2.2.9 on 2020-03-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200130_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='akcja',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nieruchomosc',
        ),
        migrations.DeleteModel(
            name='SlAkcja',
        ),
        migrations.DeleteModel(
            name='SlNieruchomosci',
        ),
    ]
